#import <Foundation/Foundation.h>

enum PigmentColor {
  PIGMENT_UNDEFINED = 0x0,
  PIGMENT_WHITE = 0x1,
  PIGMENT_BLACK = 0x2,
  PIGMENT_RED_OCHRE = 0x3,
  PIGMENT_YELLOW_INDIAN = 0x4,
  PIGMENT_BLUE_ULTRAMARINE = 0x5,
  PIGMENT_EMERALD_GREEN = 0x6,
  PIGMENT_TYRIAN_PURPLE = 0x7,
  PIGMENT_BLUE_COPPER = 0x8,
  PIGMENT_COLOR_COUNT = 0x9,
};
